services:
  mongo-rs0:
    hostname: mongo-rs0
    container_name: mongo-rs0
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint.sh:/usr/local/bin/mongo-rs-entrypoint.sh:ro
      - ./mongo-keyfile:/run/config/mongo-keyfile:ro
    entrypoint: ["/usr/local/bin/mongo-rs-entrypoint.sh"]
