version: '3'

services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:focal
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
    - "27017:27017"

