services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27016:27017"
